# NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np
my_arr = np.arange(1000000)  #0 dan 999999 a array olusturur.
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 33.9 ms
Wall time: 1.13 s


* ndarray= n dimensional array

## The NumPy ndarray: A Multidimensional Array Object

In [4]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 2.30574441, -1.61266657, -0.45944863],
       [-0.62507778, -0.80016568,  0.85063611]])

In [5]:
data * 10

array([[ 23.0574441 , -16.1266657 ,  -4.5944863 ],
       [ -6.25077779,  -8.00165678,   8.50636114]])

In [6]:
data + data

array([[ 4.61148882, -3.22533314, -0.91889726],
       [-1.25015556, -1.60033136,  1.70127223]])

In [7]:
data.shape

(2, 3)

* Numpy array homojen olmak zorunda mi? dene.

**Evet zorunda, homojen degilse donusturmeye calisir kapsayici ture.**

In [8]:
data.dtype

dtype('float64')

### Creating ndarrays

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

**Duz python dan farkli olarak hem homojen olmak zorunda hem de boyut elemanlariayni uzunlukta olmak zorunda.**

In [11]:
data2 = [[1, 2, 3,4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(5,15,2)

array([ 5,  7,  9, 11, 13])

### Data Types for ndarrays

In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [24]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [26]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [27]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [28]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [29]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [30]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [31]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

* u4: unsigned 32

In [32]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Arithmetic with NumPy Arrays

In [33]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [38]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5]

5

In [42]:
arr[5:8]

array([5, 6, 7])

In [43]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

* Yukaridaki normal python array inde yapilsa 3 unun yerine yalniz bir tane 12 atanirdi, burada hepsine atadi. Buna broadcasting denir.

In [44]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [45]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [46]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

* Yani yukaridaki olayda slicing ile kopya degil bir parcasini degistirmis oluyoruz. Yeni bir ad atamasi altinda olsa dahi degisiyor. Illa kopyasini istiyorsa .copy() kullan.

In [47]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [48]:
arr2d[0][2]

3

In [49]:
arr2d[0, 2]

3

In [51]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d.shape

(2, 2, 3)

In [60]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3d[1, 0]

array([7, 8, 9])

* Ustte elde ettigin eksik index-array dim iliskisini irdele.

In [64]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [65]:
x[0]

array([7, 8, 9])

#### Indexing with slices

In [66]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [67]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [68]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

* Iki boyutlu matriste asagidaki islemi indexing ile yapamiyormusuz. Aradaki farki incele.

In [70]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [71]:
arr2d[1, :2]

array([4, 5])

* Eger indexleri ve slicing i karistirirsan daha az boyutlu bir matris elde edersin

In [72]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[:2, 2]

array([3, 6])

In [74]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [76]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [77]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [78]:
data = np.random.randn(7, 4)
data

array([[-0.59031531, -0.02342806, -0.2472008 ,  0.27028017],
       [ 2.47859225, -0.37620634,  0.15302512,  0.92834852],
       [ 0.43796434,  0.33653408, -0.15048748, -0.08794394],
       [ 0.5267124 ,  0.37115312,  1.19309033,  1.88300064],
       [-0.04768949,  0.15164638, -0.91469579,  1.31450036],
       [-0.74023509, -0.51590104, -0.70394077, -1.04507655],
       [-0.11293696, -1.11057017, -1.15779716,  2.30046093]])

In [79]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [80]:
data[names == 'Bob']

array([[-0.59031531, -0.02342806, -0.2472008 ,  0.27028017],
       [ 0.5267124 ,  0.37115312,  1.19309033,  1.88300064]])

In [81]:
data[names == 'Bob', 2:]

array([[-0.2472008 ,  0.27028017],
       [ 1.19309033,  1.88300064]])

In [82]:
data[names == 'Bob', 3]

array([0.27028017, 1.88300064])

* yukarida 3 ve 3: farkini incele.

In [83]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

* Numpy da and or not yok. & | ~ var.

In [84]:
data[~(names == 'Bob')]

array([[ 2.47859225, -0.37620634,  0.15302512,  0.92834852],
       [ 0.43796434,  0.33653408, -0.15048748, -0.08794394],
       [-0.04768949,  0.15164638, -0.91469579,  1.31450036],
       [-0.74023509, -0.51590104, -0.70394077, -1.04507655],
       [-0.11293696, -1.11057017, -1.15779716,  2.30046093]])

In [85]:
cond = names == 'Bob'
cond

array([ True, False, False,  True, False, False, False])

In [86]:
data[~cond]

array([[ 2.47859225, -0.37620634,  0.15302512,  0.92834852],
       [ 0.43796434,  0.33653408, -0.15048748, -0.08794394],
       [-0.04768949,  0.15164638, -0.91469579,  1.31450036],
       [-0.74023509, -0.51590104, -0.70394077, -1.04507655],
       [-0.11293696, -1.11057017, -1.15779716,  2.30046093]])

In [87]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [88]:
data[mask]

array([[-0.59031531, -0.02342806, -0.2472008 ,  0.27028017],
       [ 0.43796434,  0.33653408, -0.15048748, -0.08794394],
       [ 0.5267124 ,  0.37115312,  1.19309033,  1.88300064],
       [-0.04768949,  0.15164638, -0.91469579,  1.31450036]])

In [87]:
data<0

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

In [89]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.        , 0.27028017],
       [2.47859225, 0.        , 0.15302512, 0.92834852],
       [0.43796434, 0.33653408, 0.        , 0.        ],
       [0.5267124 , 0.37115312, 1.19309033, 1.88300064],
       [0.        , 0.15164638, 0.        , 1.31450036],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.30046093]])

In [90]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [2.47859225, 0.        , 0.15302512, 0.92834852],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.30046093]])

### Fancy Indexing

asagidaki listeyi compre ile yap. Yaptim xD

In [93]:
arrk=[[x,x,x,x] for x in range(8)]
arrk

[[0, 0, 0, 0],
 [1, 1, 1, 1],
 [2, 2, 2, 2],
 [3, 3, 3, 3],
 [4, 4, 4, 4],
 [5, 5, 5, 5],
 [6, 6, 6, 6],
 [7, 7, 7, 7]]

In [91]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [95]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [96]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [97]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [98]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [100]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

* 1,5,7,2 . satirlarin tum sutunlarini 0,3,1,2 sirasiyla al.

### Transposing Arrays and Swapping Axes

In [101]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [103]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [104]:
arr
arr.swapaxes(0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [105]:
arr = np.random.randn(6, 3)
arr

array([[-1.07307118, -0.68017147,  0.22918459],
       [-1.03870379,  0.34997101, -0.70391368],
       [-1.32542757,  0.74684884,  0.28963841],
       [ 0.57141173,  0.192639  ,  0.60668205],
       [ 0.56051631,  1.69174102,  0.47848802],
       [-0.04770408,  0.41509878,  2.27448557]])

In [106]:
np.dot(arr.T, arr)

array([[4.63011116, 0.41498484, 0.60769504],
       [0.41498484, 4.21430058, 1.68456652],
       [0.60769504, 1.68456652, 6.40220897]])

yukarida dot carpimi yapmis. Onu hatirla.

## Universal Functions: Fast Element-Wise Array Functions

Element wise: Arrayin her elemanina belirtilen islemi uygular. Veya iki arrayin ayni yerdeki elemanlarina karsilikli ayni islemi uygular.

In [107]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [118]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [119]:
x = np.random.randn(8)
x

array([ 1.29307343, -0.58374807,  0.03464469, -1.22275658,  0.37100391,
        0.62103329,  0.84586517,  0.89038962])

In [120]:
y = np.random.randn(8)
y

array([ 0.44671941,  2.10949422,  0.20362199, -1.78201351,  1.61099285,
        0.36848888, -1.71730285,  0.8312593 ])

In [121]:
np.maximum(x, y)

array([ 1.29307343,  2.10949422,  0.20362199, -1.22275658,  1.61099285,
        0.62103329,  0.84586517,  0.89038962])

In [122]:
arr = np.random.randn(7) * 5
arr

array([ 0.63813496, -3.93550357,  1.33585852, -3.39496031, -4.94682242,
       -0.4549004 ,  1.86134921])

In [123]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.63813496, -0.93550357,  0.33585852, -0.39496031, -0.94682242,
       -0.4549004 ,  0.86134921])

In [124]:
whole_part

array([ 0., -3.,  1., -3., -4., -0.,  1.])

In [125]:
arr

array([ 0.63813496, -3.93550357,  1.33585852, -3.39496031, -4.94682242,
       -0.4549004 ,  1.86134921])

In [126]:
np.sqrt(arr)

<ipython-input-126-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([0.7988335 ,        nan, 1.15579346,        nan,        nan,
              nan, 1.36431272])

* nan acilimi: not a number

In [127]:
np.sqrt(arr, arr)
arr

<ipython-input-127-e905ecbe992a>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([0.7988335 ,        nan, 1.15579346,        nan,        nan,
              nan, 1.36431272])

bunun espirisi sqrt yi arr e atadi direkt. inplace yani.

## Array-Oriented Programming with Arrays

### Expressing Conditional Logic as Array Operations

In [128]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

* where: kosul saglaniyorsa xarr saglanmiyorsa yarr.

In [129]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [130]:
arr = np.random.randn(4, 4)
arr

array([[ 0.46766205,  0.97545323, -0.25686473, -1.30396438],
       [-1.17042159,  1.45478788,  1.3046291 , -0.39139141],
       [ 0.11183217,  0.08728251, -0.30399172,  1.21569158],
       [ 0.34149161, -1.54248249,  0.34468448,  1.16099497]])

In [131]:
arr > 0

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [ True, False,  True,  True]])

In [132]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [-2,  2,  2, -2],
       [ 2,  2, -2,  2],
       [ 2, -2,  2,  2]])

In [133]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        ,  2.        , -0.25686473, -1.30396438],
       [-1.17042159,  2.        ,  2.        , -0.39139141],
       [ 2.        ,  2.        , -0.30399172,  2.        ],
       [ 2.        , -1.54248249,  2.        ,  2.        ]])

### Mathematical and Statistical Methods

In [134]:
arr = np.random.randn(5, 4)
arr

array([[ 0.68036548,  1.86797486, -0.23045463, -0.26179148],
       [ 1.42842697,  0.39307536,  1.04528688,  0.53033726],
       [ 0.16205075,  0.29863258,  0.15063131,  0.57761907],
       [ 1.32789108, -0.30775789,  1.61801943, -0.85371906],
       [-0.17370909, -0.55945429,  1.22061759, -0.1530634 ]])

In [135]:
arr.mean()

0.4380489395047421

In [136]:
np.mean(arr)

0.4380489395047421

In [137]:
arr.sum()

8.760978790094843

In [138]:
arr.mean(axis=1)

array([0.51402356, 0.84928162, 0.29723343, 0.44610839, 0.0835977 ])

* bu axis meselesi karisti. 1 satir 0 sutun bazli gibi anladim. 0 da satirlar boyunca(=sutunlarda) 1 de sutunlarca(=satirlaca) toplanir.

In [139]:
arr.sum(axis=0)

array([ 3.4250252 ,  1.69247062,  3.80410058, -0.16061761])

In [140]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [141]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [144]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### Methods for Boolean Arrays

In [145]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

56

any de herhangi biri true ise true atar, all da hepsi true ise true atar.

In [146]:
bools = np.array([False, False, True, False])
bools.any()

True

In [147]:
bools.all()

False

### Sorting

In [148]:
arr = np.random.randn(6)
arr

array([ 2.5594952 ,  1.50245711,  0.50327322,  0.6698408 , -0.06517857,
        0.31046736])

In [149]:
arr.sort()
arr

array([-0.06517857,  0.31046736,  0.50327322,  0.6698408 ,  1.50245711,
        2.5594952 ])

In [150]:
arr = np.random.randn(5, 3)
arr

array([[ 1.2836561 , -1.14457907, -0.56816677],
       [-0.05066769,  2.21960969, -0.34152063],
       [ 0.46780628,  0.44188763,  0.914258  ],
       [-0.01638992, -0.8138003 ,  0.06517401],
       [-1.13989094, -1.53185989, -0.33292177]])

In [151]:
arr.sort(1)
arr

array([[-1.14457907, -0.56816677,  1.2836561 ],
       [-0.34152063, -0.05066769,  2.21960969],
       [ 0.44188763,  0.46780628,  0.914258  ],
       [-0.8138003 , -0.01638992,  0.06517401],
       [-1.53185989, -1.13989094, -0.33292177]])

### Unique and Other Set Logic

* setlerde islem yapmani saglar. sette elemanlarin unique olmali.

In [152]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [153]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

* Elemanlarin diger bir array de olup olmadigina bakar. 2 parametrelidir.

In [154]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## Linear Algebra

In [155]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [156]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

* Asagidaki * carpimindan farkli.

In [157]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [158]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [159]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [160]:
x @ np.ones(3)

array([ 6., 15.])