# Temel Sorular

In [1]:
#Numpy kütüphanesini import edin
import numpy as np

 0 dan 8'e kadar 3x3 lük bir numpy matrisi oluşturunuz?

In [2]:
# Z=
Z=np.arange(9).reshape((3,3))
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
#print (" Matristeki her bir elemana bir ekleyin:",...) 
Z+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#print ("Matristeki her bir elemandan 3 çıkartın :",...) 
Z-3

array([[-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [5]:
#print ("Her bir elemanın karesini bulun:", ...)
Z**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [6]:
#Matrisin en büyük elemanını bulun?
np.max(Z)

8

In [13]:
#Matristeki en büyük sütunu yazdırın
Z.max(axis=1)

array([2, 5, 8])

In [7]:
#Matrisin en küçük elemanını bulun?
Z.min()

0

In [9]:
#Matristeki en küçük satırı yazdırın?
Z.min(axis=0)

array([0, 1, 2])

In [8]:
#Matrisin transpozunu alın? 
Z.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [10]:
#Matrisin ilk iki satırının yerlerini değiştirin
Z[[1,0,2]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [11]:
#Matristeki herbir satırın kümülatif toplamını bulun
Z.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [12]:
#Matriste üçten büyük olan elemanların karesini yazdırın
Z[Z>3]**2

array([16, 25, 36, 49, 64], dtype=int32)

In [13]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
a[:2,1:3]

array([[2, 3],
       [6, 7]])

array([ [2, 3],

     [6,7]])   sonucunu almak için diziyi nerden dilimlemek lazım

# PROBLEMLER

# SORU 1

Yarıçapı ve yüksekliği 5 ila 25 cm arasında  değişen rastgele oluşturulacak 5 silindirik kap oluşturun.

a) her bir kabın içerebileceği su hacmini,

b) tüm kapların içerebileceği toplam su hacmini,

c) hangi kabın en yüksek hacmi ve ne kadarını tutabileceğini,

d) hangi kabın en az hacmi ve ne kadar tutabileceğini,

e) kaplarda bulunabilecek su hacimlerinin ortalama, medyan ve standart sapması nedir?

# Çözüm

Öncelikle 2 adımlık bir işlem gereklidir.İlk adımda 10 adet rastgele integer sayı üretilmesi beklenmektedir. Daha sonra bu üretilen değerlerin tipi , boyutu, eleman sayısdı gibi özelliklere bakılacaktır. İkinci adımda ise 5 adet silindir üretmek için 2 boyutlu bir matris oluşturulması beklenmektedir.

## 1-adım) alt sınırı 5 üst sınırı 25 olan 10 rastgele integer sayı oluşturun

In [14]:
#değişkenler
no_of_items =10
lower_limit = 5
upper_limit = 25

Not:Öğe sayısı 10'dur çünkü beş kabın her biri için 2 değere ihtiyacımız vardır - biri yarıçap için diğeri yükseklik için.

In [15]:
np.random.seed(0)
values = np.random.randint(lower_limit,upper_limit,no_of_items)

In [16]:
#print (values)
values

array([17, 20,  5,  8,  8, 12, 14, 24, 23,  9])

1D(tek boyutlu dizi elde edilmiş oldu ) Şimdi, dizide aslında 10 öğe olduğunu doğrulamak için, dizinin uzunluğu olan 10 değerini döndüren valu.size öğesini kullanabiliriz. Listede ne tür değerlerin bulunduğunu bulmak için, dizinin tamsayı sayıları içerdiğini belirten dtype ('int64') döndürecek olan değer.dtype'yi kullanabilirsiniz.

## oluşturulan dizinin kaç boyutlu olduğunu yazın

In [17]:
# ...
values.ndim

1

## oluşturulan dizinin eleman sayısını bulun

In [18]:
#...
values.size

10

## oluşturulan dizinin eleman tipini bulun

In [19]:
#...
values.dtype

dtype('int32')

## oluşturulan dizinin satır sütun sayısını bulun

In [20]:
#...
values.shape

(10,)

Yani, silindirler için yarıçap ve yüksekliklere ihtiyacımız var, ama şu anda elimizde sadece bir sayı dizisi var. Numaraları her silindir için birer tane olacak şekilde çiftler halinde görünecek şekilde yeniden düzenleyelim. Bunun için yeniden şekillendirme yöntemini kullanıyoruz.

## 5 adet silindir için diziyi 2D(iki boyutlu ) olarak ayarlayın 

In [21]:
#diziyi satır sayısı 5 sütun sayısı 2 olacak şekilde tekrar ayarlayın. 
no_of_rows =5 
no_of_columns =2 
#containers =...
containers=values.reshape(no_of_rows,no_of_columns)
containers

array([[17, 20],
       [ 5,  8],
       [ 8, 12],
       [14, 24],
       [23,  9]])

In [26]:
# print(containers)

## yeni oluşturulan dizinin boyutunu yazdırın

In [22]:
#
containers.ndim

2

## yeni oluşturulan dizinin satır sütun sayısını yazdırın

In [23]:
#
containers.shape

(5, 2)

## Dizideki ilk sütunu yarıçap ikinci sütunu yükseklik olacak şekilde dilimleyin?

In [24]:
#radius = containers[...]
radius=containers[:,0]
radius

array([17,  5,  8, 14, 23])

In [25]:
#height = containers[...]
height=containers[:,1]
height

array([20,  8, 12, 24,  9])

In [32]:
#height

## \begin{equation*} 
\text{silindirin hacmi:} 
\pi r^2h
\ 
\end{equation*}

## a-Tüm silindirlerin hacmini hesaplayın

In [26]:
volume=np.pi*(radius**2)*height

In [27]:
volume

array([18158.40553775,   628.31853072,  2412.74315796, 14778.05184249,
       14957.12262374])

## b-tüm silindirlerde bulunan suyun toplam hacmini bulun?

In [28]:
total_volume =np.sum(volume)

In [29]:
total_volume

50934.64169265132

## Toplam hacim,  silindirlerin tek tek hacimlerini hesaplamadan alternatif bir şekilde de hesaplanabilir. Bunu yapmanın yolu yarıçap ve yüksekliğin nokta çarpımını hesaplamaktır. Alternatif yolu yazın

In [30]:
radius_squared =np.square(radius)
dot_product = np.dot(radius_squared,height)
total_volume_by_dot_product =np.pi*dot_product

In [31]:
print(total_volume_by_dot_product)

50934.64169265132


## c-Hangi silindirin maksimum su hacmini tutabildiğini ve indeksini bulun?

In [32]:
max_volume =np.max(volume)
max_volume

18158.405537749004

In [33]:
index_of_max_volume =volume.argmax()
index_of_max_volume

0

## d-Hangi silindirin minimum su hacmini tutabildiğini ve indeksini bulun?

In [34]:
min_volume =volume.min()
min_volume

628.3185307179587

In [35]:
index_of_min_volume =volume.argmin()
index_of_min_volume

1

In [48]:
#print(index_of_min_volume)

## e-Son olarak, silindirlerin hacimlerinin ortalama, medyan ve standart sapmasını hesaplayabiliriz.

In [36]:
volume_mean =np.mean(volume)
volume_mean

10186.928338530264

In [37]:
volume_median =np.median(volume)
volume_median

14778.051842486386

In [38]:
volume_standard_deviation =np.std(volume)
volume_standard_deviation

7199.758245451731

In [46]:
#volume_mean

In [45]:
#volume_median

In [44]:
#volume_standard_deviation


# SORU 2

Boy_listesi ve pozisyon_listesi listeleri verilen futbolcularla ilgili aşağıdaki boşlukları doldurunuz 

In [39]:
boy_listesi = [198, 187, 184, 179, 180, 184, 195, 177, 182, 186, 185, 170, 187, 183, 173]
pozisyon_listesi = ['K','F', 'O', 'O', 'D','F', 'K', 'O', 'F', 'D', 'D','F', 'O', 'D', 'O']

In [40]:
#Boy listesini  np_boy_dizisi ve poziyon listesini np_pozisyon_dizisi adlı numpy dizilere atayın.
np_boy_dizisi =np.array(boy_listesi)
np_pozisyon_dizisi =np.array(pozisyon_listesi)

In [41]:
# Yalnız kalecilerin boylarının olduğu bir dizi oluşturun ve yazdırın.
#print(...)
k_boylar=np_boy_dizisi[np_pozisyon_dizisi=="K"]
k_boylar

array([198, 195])

In [42]:
#Diğer oyuncuların boylarının olduğu bir liste oluşturalım.
#...
#print(...)
diger_boylar=np_boy_dizisi[np_pozisyon_dizisi!="K"]
diger_boylar

array([187, 184, 179, 180, 184, 177, 182, 186, 185, 170, 187, 183, 173])

In [43]:
#Kalecilerin boy ortalamasını yazdırın.
#print(...)
np.mean(k_boylar)

196.5

In [44]:
#Diğer oyuncuların boy ortalamasını yazdıralım.
#print(...)
np.mean(diger_boylar)

181.30769230769232

# SORU 3

İnç cinsinden verilen boy uzunluklardan oluşan bir uzunluk listesi ve pound cinsinden verilen ağırlık listesi ile ilgili BMİ (Boy kilo endeksini) hesaplayınız?.
inç cinsini metreye metre çevirmek için 0.0254
pound cinsini kg olarak ile hesaplamak için 0.453592 çarpın

In [45]:

uzunluklar = [79.13385826771654, 72.83464566929134, 70.86614173228347, 73.22834645669292, 74.01574803149607, 75.59055118110236, 71.65354330708662, 72.04724409448819]
agirliklar = [185.82544665690753, 178.57457803488597, 174.16532919451842, 189.59770013580487, 205.03007107709132, 191.80232455598863, 171.96070477433466, 153.5514559339671]

In [46]:
#np_uzunluklar dizisindeki değerleri metreye çevirip, np_uzunluklar_m isimli diziye alalım.
np_uzunluklar_m =np.array(uzunluklar)*0.0254
#print(...)
np_uzunluklar_m

array([2.01, 1.85, 1.8 , 1.86, 1.88, 1.92, 1.82, 1.83])

In [47]:
#np_agirliklar dizisindeki değerleri kiloya çevirip, np_agirliklar_kg isimli diziye alalım.
np_agirliklar_kg =np.array(agirliklar)*0.453592
#print(...)
np_agirliklar_kg

array([84.288936, 81.      , 79.      , 86.      , 93.      , 87.      ,
       78.      , 69.649712])

In [48]:
#Oyuncuların BMI değerlerini hesaplayın
#...
bmi=np_agirliklar_kg/(np_uzunluklar_m)**2
bmi

array([20.86308161, 23.66691015, 24.38271605, 24.85836513, 26.31281123,
       23.60026042, 23.54788069, 20.79778793])

In [49]:
#bmi değeri 21'in altında olan oyunculardan oluşan bir hafif dizisi oluşturun ve yazdırın.
hafif=bmi[bmi<21]
#print(...)
hafif

array([20.86308161, 20.79778793])

In [50]:
#np_agirliklar_kg dizisinin 3 numaralı indeksindeki veriyi yazdırın.
#print(...)
np_agirliklar_kg[3]

86.0

In [53]:
#np_agirliklar_kg dizisinin 3. indekten 6. indekse kadar olan verileri yazdıralım(6 dahil).
#print(...)
np_agirliklar_kg[3:7]

array([86., 93., 87., 78.])